/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as PosterPosterIdRouteImport } from './routes/poster.$posterId'
import { Route as PhotosPhotoIdRouteImport } from './routes/photos.$photoId'
import { Route as HomeListingIdRouteImport } from './routes/home.$listingId'
import { Route as DocsDocIdRouteImport } from './routes/docs.$docId'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterPosterIdRoute = PosterPosterIdRouteImport.update({
  id: '/poster/$posterId',
  path: '/poster/$posterId',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosPhotoIdRoute = PhotosPhotoIdRouteImport.update({
  id: '/photos/$photoId',
  path: '/photos/$photoId',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeListingIdRoute = HomeListingIdRouteImport.update({
  id: '/home/$listingId',
  path: '/home/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocIdRoute = DocsDocIdRouteImport.update({
  id: '/docs/$docId',
  path: '/docs/$docId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/integrations': typeof IntegrationsRoute
  '/plan': typeof PlanRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/home/$listingId': typeof HomeListingIdRoute
  '/photos/$photoId': typeof PhotosPhotoIdRoute
  '/poster/$posterId': typeof PosterPosterIdRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/integrations': typeof IntegrationsRoute
  '/plan': typeof PlanRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/home/$listingId': typeof HomeListingIdRoute
  '/photos/$photoId': typeof PhotosPhotoIdRoute
  '/poster/$posterId': typeof PosterPosterIdRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/integrations': typeof IntegrationsRoute
  '/plan': typeof PlanRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/docs/$docId': typeof DocsDocIdRoute
  '/home/$listingId': typeof HomeListingIdRoute
  '/photos/$photoId': typeof PhotosPhotoIdRoute
  '/poster/$posterId': typeof PosterPosterIdRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/integrations'
    | '/plan'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/studio'
    | '/docs/$docId'
    | '/home/$listingId'
    | '/photos/$photoId'
    | '/poster/$posterId'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/integrations'
    | '/plan'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/studio'
    | '/docs/$docId'
    | '/home/$listingId'
    | '/photos/$photoId'
    | '/poster/$posterId'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/integrations'
    | '/plan'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/studio'
    | '/docs/$docId'
    | '/home/$listingId'
    | '/photos/$photoId'
    | '/poster/$posterId'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PlanRoute: typeof PlanRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  DocsDocIdRoute: typeof DocsDocIdRoute
  HomeListingIdRoute: typeof HomeListingIdRoute
  PhotosPhotoIdRoute: typeof PhotosPhotoIdRoute
  PosterPosterIdRoute: typeof PosterPosterIdRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/$posterId': {
      id: '/poster/$posterId'
      path: '/poster/$posterId'
      fullPath: '/poster/$posterId'
      preLoaderRoute: typeof PosterPosterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$photoId': {
      id: '/photos/$photoId'
      path: '/photos/$photoId'
      fullPath: '/photos/$photoId'
      preLoaderRoute: typeof PhotosPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/$listingId': {
      id: '/home/$listingId'
      path: '/home/$listingId'
      fullPath: '/home/$listingId'
      preLoaderRoute: typeof HomeListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$docId': {
      id: '/docs/$docId'
      path: '/docs/$docId'
      fullPath: '/docs/$docId'
      preLoaderRoute: typeof DocsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  IntegrationsRoute: IntegrationsRoute,
  PlanRoute: PlanRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  DocsDocIdRoute: DocsDocIdRoute,
  HomeListingIdRoute: HomeListingIdRoute,
  PhotosPhotoIdRoute: PhotosPhotoIdRoute,
  PosterPosterIdRoute: PosterPosterIdRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
